export { CarritoPage } from "./carrito/carrito";
export { CategoriasPage  } from "./categorias/categorias";
export { LoginPage } from "./login/login";
export { OrdenesPage } from "./ordenes/ordenes";
export { OrdenesDetallesPage } from "./ordenes-detalles/ordenes-detalles";
export { PorCategoriasPage } from "./por-categorias/por-categorias";
export { ProductoPage } from "./producto/producto";
export { TabsPage } from "./tabs/tabs";
export { HomePage } from "./home/home";